### ISSUE TITLE
volmip: volc-pinatubo-ini: same as DCPP 3.4

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/Request#10]
Duplication of experiment labels ...

**Comment by charliepascoe** [comment]
Data will be labelled as dcppC-forecast-addPinatubo

**Comment by charliepascoe** [comment]
That is dcppC-forecast-addPinatubo supercedes volc-pinatubo-ini

**Comment by martinjuckes** [comment]
Fixed

**Comment by JamesAnstey** [comment]
In the latest data request version (01.00.31.post3) the MIP for the dcppC-forecast-addPinatubo experiment item is VolMIP, not DCPP. Since this experiment is using the name as given in the Boer et al. DCPP GMD paper, shouldn't its defining MIP be given as DCPP, not VolMIP?
