### ISSUE TITLE
lithk on both IyrGre and IyrAnt tables set to time invariant

### ISSUE THREAD

**Issue by sherimickelson** [cmip6dr/Request#101]
We noticed that some time in the last couple of releases, these variables were changed to be time invariant when they shouldn't be.

The variables are lithk on both the IyrGre and IyrAnt tables:
http://clipc-services.ceda.ac.uk/dreq/u/d5b3990e-c78d-11e6-9b25-5404a60d96b5.html
http://clipc-services.ceda.ac.uk/dreq/u/d5b43076-c78d-11e6-9b25-5404a60d96b5.html

**Comment by martinjuckes** [comment]
Thanks for pointing it out: also `hfgeoubed`.

Fixed in 01.00.31
