### ISSUE TITLE
sconc* variable 

### ISSUE THREAD

**Issue by oligan** [cmip6dr/Request#102]
It looks like surface concentrations of SO4 and dust (sconcso4 and sconcdust) are requested in scenarioMIP but not surface concentrations of other aerosol species. I think sconcbc, sconcno3, sconcoa, sconcss should be treated the same as sconcso4 and sconcdust in ScenarioMIP. Likewise for the historical simulation, all sconc* variables should be treated the same (at the moment only sconcso4, sconcss, sconcdust are requested).

**Comment by martinjuckes** [comment]
I'm afraid `sconcbc` etc. are not included in the CMIP6 data request. The request is based on the requirements expressed by the MIPs ... I'm afraid I can't comment on why nobody requested these variables.
