### ISSUE TITLE
New FAFMIP Experiments

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/Request#119]
Described in issue [CV #797](https://github.com/WCRP-CMIP/CMIP6_CVs/issues/797).

@JonathanGregory : what is the data request for these new experiments? Should it be the same as `faf-all` or `faf-heat`?

**Comment by JonathanGregory** [comment]
The new FAFMIP experiments are like faf-heat for diagnostics. Thanks for asking.

**Comment by durack1** [comment]
@martinjuckes @taylor13 the relevant linked issue is
WCRP-CMIP/CMIP6_CVs#797

**Comment by martinjuckes** [comment]
Linked to the Fafmip1 group, as for `faf-heat` (01.00.32).
