### ISSUE TITLE
New DAMIP experiment

### ISSUE THREAD

**Issue by durack1** [cmip6dr/Request#120]
@martinjuckes @taylor13 the relevant linked issues are
WCRP-CMIP/CMIP6_CVs#839
WCRP-CMIP/CMIP6_CVs#838

**Comment by martinjuckes** [comment]
@durack1 : please stop spamming this repository/

**Comment by durack1** [comment]
@martinjuckes you requested that @taylor13 was to open issues in this repository to address the REOPENED issues in the CMIP6_CVs, it's in the minutes of the 10th March 2020 call, see item 9c at http://bit.ly/WGCMWIP200310

`
ACTION: Karl and Paul to reopen CV issues that defined new experiments and expedite addition to the data request and ES-DOCs.  Issues shouldn't be closed out until the information has been propagated. THIS HAS BEEN DONE (see issues 739, 759, 760, 781, 797, 805 at https://github.com/WCRP-CMIP/CMIP6_CVs/issues/885#issuecomment-595674612
`

In the 24th March meeting you requested that @taylor13 open "data request issues", see notes under item 3 at https://bit.ly/WGCMWIP200324

`
ACTION ITEM: Data request issues need to be generated (KARL) (https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions) outlining which existing experiment will provide the request that needs to be copied for the new experiment, and linked to the open CMIP6_CVs issue
`

**Comment by martinjuckes** [comment]
@durack1 : what is the information that needs to be propagated? We need to discuss this again. What you are doing is just disruptive. 

Date request issues do need to be generated, but they should be about the data request. We can try to clarify at the meeting next week..

**Comment by durack1** [comment]
@martinjuckes a noted in [WCRP-CMIP/CMIP6_CVs#838](https://github.com/WCRP-CMIP/CMIP6_CVs/issues/838#issuecomment-558880259) the data request for `hist-totalO3` intended to follow the existing `hist-aer`. @npgillett confirmed this via email, not in the issue dialogue

> @npgillett I assume the data request for this experiment will follow the same template as `hist-aer` etc?
