### ISSUE TITLE
RFMIP experiment clarification

### ISSUE THREAD

**Issue by durack1** [cmip6dr/Request#121]
@martinjuckes @taylor13 the relevant linked issue is
WCRP-CMIP/CMIP6_CVs#781

**Comment by martinjuckes** [comment]
If there is an issue related to the data request, post it here.

**Comment by durack1** [comment]
@martinjuckes if this issue is now resolved from a data request point of view, it would be useful to also let us know so we can close the open issues that are waiting your action and feedback. For RFMIP it's WCRP-CMIP/CMIP6_CVs#781
