### ISSUE TITLE
Register 4 new PMIP experiments

### ISSUE THREAD

**Issue by durack1** [cmip6dr/Request#123]
@martinjuckes 4 new PMIP experiments are currently in discussion at WCRP-CMIP/CMIP6_CVs#898.

Discussions are ongoing, and no existing experiment data request template has been defined, even though this question has been raised. Until the appropriate data request information is available, there is nothing to do here.

Ping @taylor13 @charliepascoe @davidhassell @jypeter
Ref ES-DOC/esdoc-project#83

**Comment by jypeter** [comment]
@martinjuckes let me know if I should provide extra information here, once @durack1 has fixed two copy/paste problems in the CV

**Comment by martinjuckes** [comment]
@jypeter : I'll add these to the [PMIP3 experiment group](http://clipc-services.ceda.ac.uk/dreq/u/f16f0c56-dd9e-11e6-b89b-ac72891c3257.html) .. which currently only contains `past1000`

**Comment by martinjuckes** [comment]
Experiments added in 01.00.33: 

esm-past1000
past1000-solaronly
past1000-volconly
past2k
