### ISSUE TITLE
PAMIP - annual means requested for experiments that do not include a complete calendar year

### ISSUE THREAD

**Issue by sol1105** [cmip6dr/Request#127]
PAMIP defines experiments that start in April and end in May the following year.
For example:
pdSST-pdSIC
description: "[...]  Time slice simulations to begin on 1st April and run for 14 months, the first two months are ignored to allow for an initial model spin up. Minimum ensemble size is 100 simulations."

PAMIP requests annual mean data for this experiments:
baresoilFrac | Eyr
cropFrac | Eyr
grassFrac | Eyr
residualFrac | Eyr
shrubFrac | Eyr
treeFrac | Eyr
vegFrac | Eyr
zfullo | Eyr

Should this annual means be provided from June to May of the next year or should they be removed from the PAMIP data request for this experiments?

Kind regards
Martin

**Comment by martinjuckes** [comment]
I think it would be disruptive to change the request now, but it should be fixed in the next phase of CMIP. I've marked it for attention in the "forward look" repository .. see above.
