### ISSUE TITLE
Day variable groups

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/Request#16]
The "day_oth" and "day_ss" groups have been switched wrt. CMIP5 as far as the variables in the groups are concerned, so the time periods requested in the 01.00.00 request are wrong. This should be fixed soon. Worth also improving the naming and titles of the variable groups.

**Comment by taylor13** [comment]
@martinjuckes Was this corrected in the recent release?  I think this affects the DECK so needs to be corrected immediately if it hasn't already.  Otherwise, certain important daily variables won't be saved.  [If I understand this correctly.]

**Comment by martinjuckes** [comment]
fixed
