### ISSUE TITLE
GeoMIP: update the description for the "climate forcing" objective

### ISSUE THREAD

**Issue by charliepascoe** [cmip6dr/Request#18]
Remove the string "-u2014-" from the description.

description[i]: One of the goals of GeoMIP is to understand the Earth System's response to climate forcing agents -u2014- both single forcing agents and combinations of forcings.
title[i]: climate forcing
label[i]: Forcing
mip[i]: [mip] GeoMIP [GeoMIP]
uid[i]: 7170ef54-c6fd-11e6-8aa7-ac72891c3257

**Comment by martinjuckes** [comment]
Fixed
