### ISSUE TITLE
HighResMIP: re-order the list of objectives

### ISSUE THREAD

**Issue by charliepascoe** [cmip6dr/Request#20]
The HighResMIP have requested that we re-order the list of objectives to better reflect the priorities of the HighResMIP.

1 -> 8
2 -> 6
3 -> 3
4 -> 1
5 -> 4
6 -> 7
7 -> 2
8 -> 5

Note that the objectives that there are 7 objectives on the CMIP6 data request but 8 on the es-doc site http://documentation.es-doc.org/cmip6/mips/highresmip  Apart from the addition of a request for variables to coordinate with CORDEX the objectives listed by es-doc are in the same order as those in the cmip6dr, therefore it is best that any modification be done at the cmip6dr end.

**Comment by martinjuckes** [comment]
@charliepascoe : HighResMIP did, at one stage, have a request for variables to support CORDEX, but that has now been withdrawn. So, there are 7 objectives -- now the same in the data request and the ES-DOC link above. How should these 7 be re-ordered?

**Comment by martinjuckes** [comment]
Expired
