### ISSUE TITLE
VolMIP: Update objectives

### ISSUE THREAD

**Issue by charliepascoe** [cmip6dr/Request#22]
VolMIP have requested that we update three of their objectives as follows: 

Dynamics: Improve understanding of the (seasonal to interannual) mechanisms underlying the dynamical atmospheric response to large volcanic eruptions, in particular separating indirect responses from the direct radiative response; improve understanding of decadal feedback mechanisms induced in the coupled ocean-atmosphere system by large volcanic eruptions

Evaluation: Evaluate models against observations. Improve understanding of the role of background climate conditions in determining the climate response to the 1991 Pinatubo eruption. The evaluation must take into account the idealized character of VolMIP experiments.

Paleo: Evaluate models against paleo reconstructions This objective is motivated by the mismatch between simulated and reconstructed post-eruption surface cooling for volcanic eruptions during the last millennium. The evaluation must take into account the idealized character of VolMIP experiments.

**Comment by martinjuckes** [comment]
Done for next upgrade
