### ISSUE TITLE
including fields needed for parametric vertical coordinates

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/Request#26]
For CMOR developers, it would greatly simplify things if when a variable has been requested on atmospheric model levels (as opposed to pressure levels), you could add to the table (containing that variable) surface_air_pressure (ps).

For hybrid sigma coordinate models, we need to store surface pressure, ps(lon, lat, time) so that (using the "A" and "B" coefficients) we can convert model level to pressure.  In order for CMOR to store ps, ps needs to appear in the same table as the output variable.  So to output air temperature (ta) on model levels, ps must be found in the same table as ta.  (Then ps gets stored along with ta in the netCDF file. The cleanest way to do this would be to add "ps" to any table where atmos. model level data is called for. So would it be too difficult to add a couple of variables to some of the tables?  Specifically

Add ps(lon, lat, [time])  to the following tables:
AERmon
CF3hr
CFmon
E3hrPt
E6hrZ
Emon
Esubhr
and possibly Efx (if that table is correct as is).
(ps already appears in Amon, 6hrLev, CFsubhr, and CFday, which are the other tables containing atmospheric data stored on model levels.)

ps should have all the same specifications as in table Amon *except* cell_measures should be the same as the cell_measures defined for the variables that will be archived on model levels and similarly for the time and lat/lon dimensions.   For example, in table E3hrPt, the cell_methods for ps should be "time: point" (not "time: mean"), and the dimensions should be "longitude latitude time1" (not "longitude latitude time").

The other so-called z-factors can be gotten by CMOR from an auxiliary table (we create) because the time sampling characteristics are always the same (for all output fields), but ps has different time-sampling characteristics depending on which table it is in.  That's why ps is a special case.

**Comment by martinjuckes** [comment]
Done
