### ISSUE TITLE
Names of some PMIP experiments should be updated

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#27]
@martinjuckes I hope this is the right place to list DR related problems!

DR **01.00.04** still uses the old (temporary) names for some of the PMIP experiments. The following should be updated in order to match the official names in the experiments' CV file: https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json

- Last Interglacial: change _LIG_ to **lig127k**
- Mid Pliocene Warm Period: change _PlioExp_ to **midPliocene-eoi400**

**Comment by martinjuckes** [comment]
Fixed in 01.00.11
