### ISSUE TITLE
Can mcd be defined in TWO mon tables: CFmon and Emon? (DR 01.00.04)

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#29]
I have just noticed that mcd was defined in _CFmon_ in the CMIP5 standard_output and is now (CMIP6_MIP_tables.xlsx DR 01.00.04) **defined in both CFmon and Emon**

The only difference is the **vertical levels**:
- **alevhalf** for CFmon
- **alevel** for Emon

Is this allowed?

**Comment by jypeter** [comment]
I'm guessing this is allowed but can somebody else confirm and close the issue?

I have just seen the case of **hus** that is defined on 19 levels in Amon and on 7 completely different levels in Emon...

**Comment by martinjuckes** [comment]
mcd (also mcu and some others): the Emon versions are an error: will be removed in 01.00.06

hus on different sets of levels: unfortunately this is requested .... but the 7 level version is only required if you are supporting the HighResMIP "extreme events" objective.
