### ISSUE TITLE
"Orphan" (no MIP requesting) variables in Emon (DR 01.00.04)

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#30]
When looking at the **xlsx** version of **DR 01.00.04**, I have noticed that several variables don't seem to be related to any project (i.e. nothing in the _MIPs (requesting)_ and _MIPs (by experiment)_ columns), even if they have a project listed in the _prov_ column. Is this due to a processing problem of dreqPy?

xlsx file = http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest/dreqPy/docs/CMIP6_MIP_tables.xlsx

Note that these "orphan" variables can correctly be found in _A searchable list of variables in the request_ (http://clipc-services.ceda.ac.uk/dreq/mipVars.html)

Examples:
- **mcd** : defined in 2 mon tables (see #29 because I don't know if this is OK), requested by AerChemMIP,CFMIP,GeoMIP,HighResMIP in CFmon, and by no project in Emon
- **columnmassflux** : no requesting project in Emon
- **clwvic**: no requesting project in Emon, but requested by CFMIP in Eday!
- **uqint** : no requesting project in Emon
- **vqint** : no requesting project in Emon
- **hus** : no requesting project in Emon, but lots of requesting projects in other tables
- **od550aerso**: no requesting project in Emon. But it has been requested by PMIP, as well as several other "orphan" variables. I have checked the _New variables_ and _PMIP-aero_ tabs in the PMIP xls request file and have not found anything obviousyly wrong
- etc...

**Comment by martinjuckes** [comment]
Fixed in 01.00.06
