### ISSUE TITLE
PMIP Amon variables present in html view are not requested by PMIP in CMIP6_MIP_tables.xlsx

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#32]
For the PMIP project, we have selected several (59) variables from the original PMIP5 standard_output table by editing the priority of the variable in the original xls file (see https://pmip4.lsce.ipsl.fr/doku.php/database:pmip4request#the_pmip4_request)

All these selected variables can be found when you check the html view of the PMIP-Amon table : http://clipc-services.ceda.ac.uk/dreq/u/efc08328-5629-11e6-9079-ac72891c3257.html

But when you check `CMIP6_MIP_tables.xlsx` (http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest/dreqPy/docs/CMIP6_MIP_tables.xlsx) you have **only 17 variables** that have PMIP in the _MIPs (requesting)_ column

This is a problem, because when we use `drq -m PMIP --xls` to create a list of PMIP variables (eg variables requested explicitely by PMIP) to add to the GMD papers and distribute to the PMIP participants, we get only 17 variables in Amon

It's possible we have the same problem in other tables than Amon, but I'm still working on Amon...

**Comment by martinjuckes** [comment]
For some reason the variables have been taken from another table .. I'll fix this in 01.00.09

Also applies to:
LS3MIP-L3hr LS3MIP: LS3MIP-L3hr set(['3hr', 'mon'])
DCPP-Amon DCPP: DCPP-Amon set(['subhr', 'mon'])
CFMIP-Amon CFMIP: CFMIP-Amon set(['subhr', 'mon', 'monClim'])
HighResMIP-Amon HighResMIP: HighResMIP-Amon set(['subhr', 'mon', 'monClim'])
ISMIP6-Amon ISMIP6: ISMIP6-Amon set(['subhr', 'mon'])
PMIP-Oyr PMIP: PMIP-Oyr set(['yr', 'mon'])
PMIP-Amon PMIP: PMIP-Amon set(['subhr', 'mon', 'monClim'])
