### ISSUE TITLE
CMIP6_MIP_tables.xlsx for 01.00.06 says 01.00.05

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#34]
@martinjuckes can you check the http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest/dreqPy/docs/CMIP6_MIP_tables.xlsx file accessible from https://earthsystemcog.org/projects/wip/CMIP6DataRequest?

The current version of the DR is _01.00.06_, but **the Request Version in the Notes sheet says 01.00.05**

By the way, I append the version number to the xlsx file name when I download it (eg CMIP6_MIP_tables_01.00.06.xlsx). Would it be possible to have this directly on the web page, rather than the generic _CMIP6_MIP_tables.xlsx_. I don't know how much of this is automated or done by hand

**Comment by jypeter** [comment]
I have generated some new xls files with the 01.00.06 version of dreqPy, and the the few files I have checked **also have the 01.00.05 version** in the _Notes_ sheet. I guess the DR version is coming from 2 different places and has somehow become inconsistent...

```
$ pip install --upgrade dreqPy
Collecting dreqPy
  Downloading dreqPy-01.00.06.tar.gz (1.8MB)
    100% |################################| 1.8MB 215kB/s
Building wheels for collected packages: dreqPy
  Running setup.py bdist_wheel for dreqPy ... done
  Stored in directory: /home/users/jypeter/.cache/pip/wheels/b5/7a/f8/9d8eec4920                                                                                                                                                                                                                                             01fac06271bd56299084840d0eaf1147f86abcc3
Successfully built dreqPy
Installing collected packages: dreqPy
  Found existing installation: dreqPy 1.0.5
    Uninstalling dreqPy-1.0.5:
      Successfully uninstalled dreqPy-1.0.5
Successfully installed dreqPy-1.0.6

$ drq -v
dreqPy version 01.00.06 [Version 01.00.06]
Running in python sys.version_info(major=2, minor=7, micro=12, releaselevel='fin                                                                                                                                                                                                                                             al', serial=0)

$ drq -m PMIP -p 3 --xlsDir xls6 --xls
Created directory xls6 for: xls files
[...]
```

**Comment by jypeter** [comment]
More evidence. Hope this helps. I guess the original idea was to be able to track changes separately in dreqPy in the DR itself
```
>>> from dreqPy import dreq
>>> dq = dreq.loadDreq()
>>> dq.version
'01.00.05'
>>> dq.softwareVersion
'01.00.06'
```

**Comment by martinjuckes** [comment]
The version label in the XML was not updated correctly. Fixed in later versions.
