### ISSUE TITLE
Update the PMIP URL to 'PMIP4'

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#35]
I think it would make more sense to directly use the URL of the **current phase or PMIP**, phased with CMIP6, rather than the generic URL. Can you change the URL so that we have https://pmip4.lsce.ipsl.fr/ below? Thanks!
```
>>> dq.coll['mip'].items[15].label
'PMIP'
>>> dq.coll['mip'].items[15].url  
'https://pmip.lsce.ipsl.fr/'
```

**Comment by martinjuckes** [comment]
Done (for 01.00.07)
