### ISSUE TITLE
Inconsistency online version of PMIP tables and PMIP tables returned by dreqPy

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#36]
The following is with **version 01.00.06**

Am I doing something wrong below, or is there an inconsistency problem?

## Getting the tables

A) When I look at the online version of the "tables" with variables requested by PMIP, I get **25 tables**

http://clipc-services.ceda.ac.uk/dreq/u/PMIP.html
```
PMIP-6hr {PMIP}: 5 variables, 1 request links
PMIP-6hrLev {PMIP}: 5 variables, 1 request links
PMIP-6hrPlev {PMIP}: 0 variables, 0 request links
PMIP-Aclim {PMIP}: 0 variables, 1 request links
[...]
```
B) If I use dreqPy to get (I think) the same list, I get **24 tables**
```
>>> from dreqPy import scope
>>> help(scope)
>>> sc = scope.dreqQuery()
>>> pmipl = sc.getRequestLinkByMip('PMIP')
>>> for (a,b) in enumerate(pmipl):
...   print a, b
0 Item <3.3 Request link: linking a set of variables and a set of experiments>: [PMIP-CFday] PMIP.CFday
1 Item <3.3 Request link: linking a set of variables and a set of experiments>: [PMIP-PMIP-6hr] PMIP.PMIP-6hr
[...]
```

## Problem
The following 2 are **in A but not in B**
```
    PMIP-6hrPlev {PMIP}: 0 variables, 0 request links
    PMIP-CFmon-02 {PMIP}: 0 variables, 0 request links
```
The following is **in B but not in A**
`15 Item <3.3 Request link: linking a set of variables and a set of experiments>: [fx] fx`

**Comment by martinjuckes** [comment]
(A) is a list of groups, (B) is a list of links: See https://github.com/cmip6dr/Request/issues/37 for some more explanation
