### ISSUE TITLE
fx group partially missing in the online version of the DR (by MIP) ?

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#37]
When I open the online version of the PMIP request (but I get the same with the other projects), http://clipc-services.ceda.ac.uk/dreq/u/PMIP.html, 

from the http://clipc-services.ceda.ac.uk/dreq/index/mip.html page,

I don't find the **fx** table in the 3.1 panel (_Request variable group_), but I can find it in the 3.3 panel (_Request links_)

Shouldn't fx be also present in 3.1 ?

I admit I have a hard time understanding the difference between _3.1_ and _3.3_, so maybe this is a feature and not a bug. Is there a document I can read to better understand the underlying _links concept_ ?

**Comment by martinjuckes** [comment]
The documentation is here: http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest/dreqPy/docs/dreqML.pdf . It probably needs some improvement. 

The variable groups listed under http://clipc-services.ceda.ac.uk/dreq/u/PMIP.html are those defined by PMIP, under the links tab, you find everything requested .. which generally includes references to groups defined by PMIP and groups defined by other MIPs.

**Comment by jypeter** [comment]
I have found and read _The Request XML document and Schema_ yesterday. The details and especially the table on page 8 help a lot, but I confess still have some trouble figuring out the difference between 3.1 and 3.3

If check **fx** in 3.3 for PMIP, I get 
`PMIP:fx: Link to group: CMIP6 CMOR Table: fx [14]`
and if I check it for PMIP I get
`CMIP:fx: Link to group: CMIP6 CMOR Table: fx [14]`
so I understand that both PMIP and CMIP are requesting the same thing. But why is this not in 3.1?

And the fact that this mentions **one** CMOR table, but we have **two** tabs (fx and Ofx) in CMIP6_MIP_tables.xlsx is a bit confusing (#38)

**Comment by martinjuckes** [comment]
Some variable groups (e.g. http://clipc-services.ceda.ac.uk/dreq/u/0bb7eb9e-7f05-11e6-b027-ac72891c3257.html ) are requested by many MIPs, each for a different combination of experiments, so each MIP has a different requestLink associated with this one variable group.  This makes it easier to be clear that they are all asking for exactly the same set of variables.
