### ISSUE TITLE
Move fx and Ofx tabs together, in CMIP6_MIP_tables.xlsx

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#38]
Would it be possible to have the **Ofx** and **fx** tabs in [CMIP6_MIP_tables.xlsx](http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest/dreqPy/docs/CMIP6_MIP_tables.xlsx) next to each other, and at the beginning of the tabs, the way it was in the CMIP5 standard_output file?

I'm saying this because I had not seen that there was a new _Ofx_ tab and I had started to create the following issue

Subject: **Inconsistency between fx variables in the online DR and the xls file (01.00.06)**

When I look at 3.3 in http://clipc-services.ceda.ac.uk/dreq/u/PMIP.html or http://clipc-services.ceda.ac.uk/dreq/u/CMIP.html (same with the PMIP version) I get **14 fx variables**
`CMIP:fx: Link to group: CMIP6 CMOR Table: fx [14]`

But the [CMIP6_MIP_tables.xlsx](http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest/dreqPy/docs/CMIP6_MIP_tables.xlsx) document only lists **6 fx variables** in the fx tab

**Comment by martinjuckes** [comment]
Possible, but we had a decision to separate them. The next redesign will avoid making structural dependencies on design issues such as this one which cannot be agreed on easily.
