### ISSUE TITLE
masscello missing in"CMIP6 CMOR Table: fx" ?

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#39]
**masscello is missing** from http://clipc-services.ceda.ac.uk/dreq/u/ef12e6f0-5629-11e6-9079-ac72891c3257.html, but present in Ofx in CMIP6_MIP_tables.xlsx

Is this normal?

Also, we have **orog 2 times** in the page listed above

**Comment by martinjuckes** [comment]
Fixed in 01.00.08. Orog is in the above link twice because above link is a variable group containing both a fixed and a monthly version of orog ... only one of which is needed.
