### ISSUE TITLE
v01.00.10: disconnected CMOR variables

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/Request#40]
The following CMOR variables do not appear to be connected to any request variable object, and therefore they will not appear in any experiment lists generated from this version of the data request:

 * CFsubhrOff/cfadDbze94
 * CFsubhrOff/cfadLidarsr532
 * CFsubhrOff/clcalipso
 * CFsubhrOff/clcalipso2
 * CFsubhrOff/clhcalipso
 * CFsubhrOff/cllcalipso
 * CFsubhrOff/clmcalipso
 * CFsubhrOff/cltcalipso
 * CFsubhrOff/parasolRefl
 * AERmon/ps
 * CF3hr/ps
 * CFmon/ps
 * E3hrPt/ps
 * E6hrZ/ps
 * Efx/ps
 * Esubhr/ps
 * Ofx/ugrid
 * fx/zfull

**Comment by martinjuckes** [comment]
- The "ps" variables are there to support CMOR, which inlcudes these variables when a pressure level variable in that table is requested: hence ps is needed in multiple tables even when not requested.
- cfSubhrOff: will be removed
- ugrid and fx/zfull: these need to be added into a request ... work in progress.

**Comment by jypeter** [comment]
I was going to report _no project requesting fx/zfull_ when I found this issue :)

**Comment by martinjuckes** [comment]
Fixed
