### ISSUE TITLE
Please add 2D variables to [CFMIP-CF3hr] CFMIP: CFMIP-CF3hr

### ISSUE THREAD

**Issue by markwebb24** [cmip6dr/Request#45]
Dear Martin,

The original CMIP5 spreadsheet had an entry in the cf3hr worksheet indicating that all 2D variables in Amon (except tasmax and tasmin) should be replicated in cf3hr.  Unfortunately this doesn't seem to have been picked up in the CMIP6 DR.  I'd be grateful if the following 2D variables could be added to CFMIP-CF3hr.  Please note that these should be instantaneous values, not 3 hourly means, to be consistent with the 3D variables already present in CFMIP-CF3hr.

Many thanks,
Mark

ci
clivi
clt
clwvi
evspsbl
hfls
hfss
hurs
huss
pr
prc
prsn
prw
psl
rlds
rldscs
rlus
rlut
rlutcs
rsds
rsdscs
rsdt
rsus
rsuscs
rsut
rsutcs
rtmt
sbl
sci
sfcWind
tas
tauu
tauv
ts
uas
vas

**Comment by markwebb24** [comment]
PS please note that this as a similar issue to the one which arose with the cfsites data, and which was resolved previously.

**Comment by martinjuckes** [comment]
Dear Mark,
there is a line in the CFMIP "Request Scoping" sheet saying that the cf3hr_grid group, which covers these 2d fields should be deleted. The 2d 3-hourly variables from cf3hr are currently not requested for any experiments, so it would make more sense to remove the group -- unless the intention is that they should be requested, in which case I need some information about the experiments they are needed for,

regards,
Martin

**Comment by markwebb24** [comment]
Dear Martin,

I now realise that I made a mistake when filling out the CFMIP Request scoping sheet.  The cf3hr_grid group should have been requested for the single year of 2008 in the AMIP experiment, the same as the current cf3hr-sim-new.  I'm sorry for the mistake.  

So I'd be grateful if you could add the 2D variables listed above to [CFMIP-CF3hr] CFMIP: CFMIP-CF3hr and request it in the AMIP experiment for the year of 2008.

Many thanks,
Mark

**Comment by martinjuckes** [comment]
Four exist as 3-hourly instantaneous fields in MIP table '3hr', and will be added to the CFMIP-CF3hr-grid group :  huss tas uas vas
Three are in E3hrPt, and should be moved to cf3hr and added to CFMIP-CF3hr-grid: psl rsuscs ts
21 exist as 3-hourly time mean fields (clivi clt clwvi hfls hfss pr prc prsn prw rlds rldscs rlus rlut rlutcs rsds rsdscs rsdt rsus rsut rsutcs sfcWind). For these and the remaining 8 (ci evspsbl hurs rtmt sbl sci tauu tauv), new CMOR variable records are needed.

**Comment by markwebb24** [comment]
Martin,

That sounds good.  

Many thanks,
Mark

**Comment by martinjuckes** [comment]
Fixed in 01.00.12
