### ISSUE TITLE
CMIP6 CMOR Table AERday-2d contains a number of variables which are not 2D

### ISSUE THREAD

**Issue by markwebb24** [cmip6dr/Request#46]
Dear Martin,

CMIP6 CMOR Table AERday-2d seem to contain a number of variables which are not 2D - see
http://clipc-services.ceda.ac.uk/dreq/u/ee2fcab6-7e40-11e6-9b26-f192b4cee584.html

As far as I can tell, the following variables should not appear in this table because they are 3D not 2D.  They are specified with the dimensions of 2D variables, but they are all 3D quantities.  Please remove the following entries from AERday-2d:

concbb [1]: Concentration of Biomass Burning Aerosol
conccmcn [1]: Number Concentration Coarse Mode Aerosol
conccn [1]: Aerosol Number Concentration
concnmcn [1]: Number Concentration of Nucleation Mode Aerosol
concpoa [1]: Concentration of Dry Aerosol Primary Organic Matter
ec550aer [1]: Aerosol extinction coefficient
inc [1]: Ice Crystal Number Concentration
reffclwc [2]: Hydrometeor Effective Radius of Convective Cloud Liquid Water
reffclws [2]: Hydrometeor Effective Radius of Stratiform Cloud Liquid Water

It is possible that these should be in a 3D daily tables for AERCHEMIP, but I have no way of knowing.  Currently AERday-2d is requested by CFMIP, and we only want 2D daily aerosol fields.

Thanks,
Mark

**Comment by martinjuckes** [comment]
concbb, concpoa, inc only appear in the CFMIP request, so I'll remove them completely from the request. The others just need to be removed from this group.

**Comment by martinjuckes** [comment]
Done in 01.00.11
