### ISSUE TITLE
Time slices with ambiguous overlaps

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/Request#48]
Hello Karl (@taylor13 ),

for the PiControl run you have asked for 3-hourly data for the years corresponding to the last 30 years of the abrupt4xCO2 run, and HighResMIP have asked for some of these variables for years corresponding to 1850-2049 in the historical + scenario runs. These two time slices could be overlapping or they could be disjoint (as far as I'm aware): how do you think we should deal with this?

Martin

**Comment by taylor13** [comment]
Honestly, I think we should ask HighResMIP to reduce the number of years they request, but I don't want to spend the time trying to convince them. [They probably think they can learn something about extremes with a long record of high frequency data.  If so, they should focus on just a few variables.]

If there were no drift in the piControl, then we could ask for an arbitrary 30-year period sample.  Most long-term drift is only apparent at depth in the ocean; the surface doesn't drift much in a well spun-up model.  For CMIP5 we said (on the 3hr table) that data should be archived for "30 years (ideally the years corresponding to years 121-150 of abrupt 4XCO2 run)".  So we didn't expect strict conformance.  I think this period was selected at the request of CFMIP.  You could contact Mark Webb (UKMO) and see if this is a rigid requirement.  

I don't think I care what 30 years are sampled, as long as the sample is taken after the spin-up period.  I certainly don't think someone should provide 230 years of piControl 3hr data.

hope this helps.

**Comment by martinjuckes** [comment]
* 30 year tied to abrupt4xCO2 branch time has been dropped. 
* HighResMIP request retained to provide robust baseline for studies of extremes.
