### ISSUE TITLE
DAMIP 42 year and core 35 year time slices

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/Request#49]
Hello Karl (@taylor13),

DAMIP have asked for data from historical and perturbed historical simulations (e.g. hist-sol) for the period 1979 to 2020. For the historical simulation this is split into a request for 36 years (1979 to 2014) from `historical` and 6 years from `historical-ext`.  There is also a CMIP request for 35 years of data (1980 to 2014), applied to a partially overlapping set of variables. 

I suspect that the DAMIP request for data from 1979 is associated with the start of a significant range of observation datasets. 

Should we adjust the CMIP request to use a 36 year slice instead of 35?

**Comment by taylor13** [comment]
Not sure I understand.  These runs are supposed to all be initiated in 1850, I think.  Is certain data requested only for the last years?  Which frequencies?  For CMIP-requested variables for years 1980-2014, I don't mind modifying that to 1979-2014.

**Comment by martinjuckes** [comment]
@taylor13 : Sorry, my mistake: the request for 35 years of data comes from C4MIP, LS3MIP and PMIP (it is for 3 hourly, daily and some monthly model level data), the 36 year request from CFMIP is for 3 hourly data.

Yes, the experiments start in 1850 in all cases.  

I'll check with the MIP co-chairs, but recommend standardising on 36 years.

**Comment by taylor13** [comment]
Sounds good.  They were probably trying to follow the CMIP5 example to start in 1980 and may not mind adding a year.

**Comment by martinjuckes** [comment]
CFMIP request extended to 1979-2015
