### ISSUE TITLE
basic missing variables in CMIP6 experiments?

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/Request#57]
In analysing the connections between CMOR variables and experiments within version 01.00.15 of the data request we've found that a set of 48 experiments (predominantly, but not exclusively, AerChemMIP) are not connected up to basic variables such as `tas`, `pr`, `ps`, `uas`, `vas` in the `Amon` miptable.

```
AerChemMIP
   hist-1950HC, hist-piAer, hist-piNTCF, histSST, histSST-1950HC, histSST-piAer, 
   histSST-piCH4, histSST-piN2O, histSST-piNTCF, histSST-piO3, piClim-2xDMS,
   piClim-2xNOx, piClim-2xVOC, piClim-2xdust, piClim-2xfire, piClim-2xss, piClim-BC, 
   piClim-CH4, piClim-HC, piClim-N2O, piClim-NH3, piClim-NOx, piClim-NTCF, piClim-O3, 
   piClim-OC, piClim-SO2, piClim-VOC, ssp370-lowNTCF, ssp370SST, ssp370SST-lowAer, 
   ssp370SST-lowBC, ssp370SST-lowCH4, ssp370SST-lowNTCF, ssp370SST-lowO3,  
   ssp370SST-ssp126Lu
DCPP
   dcppC-atl-spg
ISMIP6
   ism-amip-std, ism-asmb-std, ism-bsmb-std, ism-ctrl-std, ism-lig127k-std, 
   ism-ssp585-self, ism-ssp585-std, ssp585-withism
OMIP
   omip1, omip1-spunup, omip2, omip2-spunup
RFMIP
   rad-irf
```

The OMIP experiments may genuinely not want atmosphere variables, but I suspect the connections to the other experiments need a bit of work.

**Comment by martinjuckes** [comment]
Discussed by the WIP: I will try to come up with a proposal next week.

**Comment by MichaelSchulzMETNO** [comment]
What is the status/solution of this discussion?

**Comment by matthew-mizielinski** [comment]
No change in version 01.00.18.

**Comment by matthew-mizielinski** [comment]
The AerChemMIP experiments look more plausible as of version 01.00.20, but it would be worth further investigating  the DCPP experiment.

**Comment by martinjuckes** [comment]
Baseline request added.
