### ISSUE TITLE
Core variables in DECK experiment ensembles

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/Request#58]
Within the data request there is a core set of variables requested by the `CMIP` MIP including many basic variables (`Amon/tas`, `Amon/pr`, etc) that should be produced by all (DECK?) runs.

When I resolve the connections between experiments and CMOR variables within the data request (v01.00.15) I find that `CMIP` is only requesting this core set of variables from the first ensemble member of any given experiment (nenmax attribute of the requestItem on the route between the variable and experiment is set to 1).

Am I correct in assuming that the CMIP request for the core diagnostics should be output from every ensemble member?

If so could the `nenmax` attribute of the corresponding `requestItem`s be amended accordingly?

**Comment by martinjuckes** [comment]
This is a question for Karl (@taylor13) : at the moment the core data request is for data from one ensemble member. Data from additional ensemble members is optional: if it is not requested then it implies that none of the MIPs consider additional ensemble members as necessary for the analysis they intend to support. If you are doing more ensemble members, than requested, you are free to choose how much data to submit.

**Comment by taylor13** [comment]
I don't understand the purpose of nenmax, but for the DECK simulations we would like all the "core" CMIP variables from each member of the ensemble.  
thanks.

**Comment by matthew-mizielinski** [comment]
@taylor13, thanks for the confirmation. @martinjuckes, will you be able to get this change in for v1.00.16?

The limitation of variables to the first `nenmax` ensemble members is quite a significant item from the point of view of data volumes; it saves around a third based on my analysis of our _input_ data from the DECK + ScenarioMIP. At this stage I prefer to plan on delivering the minimum (still challenging) unless asked to do otherwise, and then deal with additional data once I'm confident that we can achieve the minimum (and we have a suitable justification).

Note that in many experiments the drop in data volumes we expect between the first ensemble member and subsequent members is large; I'm seeing a factor of up to 2-5* or so depending on the experiment and the list of MIPs to which requests are to be responded. @markelkington tells me that this was similar at CMIP5.

*based on input data volumes

**Comment by martinjuckes** [comment]
For 01.00.16 I'll change `nenmax` to -1, which means "output for all ensemble members". For the DECK experiments, there is only one ensemble member requested for all experiments other than abrupt-4xco2 (5 ensmeble members).
