### ISSUE TITLE
Spreadsheet issue: SIMIP request from ScenarioMIP

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/Request#60]
The SIMIP request from the ScenarioMIP experiments appears to have gone missing in the spreadsheets available via the [priority 1, tier 1](http://clipc-services.ceda.ac.uk/dreq/tab01_1_1.html) table. The SIMIP request is there in the [priority 3, tier 3](http://clipc-services.ceda.ac.uk/dreq/tab01_3_3.html) spreadsheets and the many of the "default" priorities for variables in these spreadsheets are 1, suggesting that something is going wrong during the spreadsheet creation process.

I've looked at a few standard sea-ice variables (`SImon/siconc`, `SImon/sithick`) and the connections within the data request do appear to be there, so I think that it is the spreadsheet production tools that are in error here.

In looking at this I also note that the basic sea-ice variables in SImon are absent from a wide variety of experiments, for example hist-bgc and ssp585-bgc in C4MIP. Is this an issue that needs addressing?

**Comment by matthew-mizielinski** [comment]
This issue is still present at v01.00.20 of the data request.

**Comment by martinjuckes** [comment]
Fixed in 01.00.21
