### ISSUE TITLE
Unusual priorities in four DAMIP requestVar objects

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/Request#63]
The following requestVar objects have unusual values for their priorities

'928eef36-267c-11e7-8933-ac72891c3257': Omon/hfcorr (priority 0)
'928f1196-267c-11e7-8933-ac72891c3257', Omon/wfcorr (priority 0),
'928eddd4-267c-11e7-8933-ac72891c3257', Omon/zhalfo (priority 108),
'928f064c-267c-11e7-8933-ac72891c3257', Omon/zfullo (priority 108)

All of these correspond to requests from DAMIP. I've checked all the other requestVar objects and these are the only entries which do not have a priority in usual set; [1, 2, 3]

**Comment by matthew-mizielinski** [comment]
Issue still present in data request version 01.00.20

**Comment by martinjuckes** [comment]
All set to `1` in  01.00.22
