### ISSUE TITLE
Which basins are in the 'basin' dimension?

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#64]
@martinjuckes @taylor13 @dnadeau4 can somebody tell me where I can find the official definition of the _basin_ dimension? More precisely which basins we are talking about? I have tried to find this information after talking to @oliviermarti about https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/190

I have failed to find that information on the [CMIP6 Data Request](https://earthsystemcog.org/projects/wip/CMIP6DataRequest) web site, but it's quite possible I did not follow the right links.

The [Spreadsheet view of the variable definitions](http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest/dreqPy/docs/CMIP6_MIP_tables.xlsx) does not have the convenient _dims_ panel that was present in the [CMIP5 standard output document](http://cmip-pcmdi.llnl.gov/cmip5/docs/standard_output.xls), so you need to find the _basin_ information somewhere else

As a last resort, I have looked at the [CMIP6_coordinate.json ](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json#L263-L288) for CMOR and found the following:
```
            "requested": [
                "atlantic_arctic_ocean", 
                "indian_pacific_ocean", 
                "global_ocean"
             ], 
```
I have also looked for _basin_ in [OMIP contribution to CMIP6: experimental and diagnostic protocol
for the physical component of the Ocean Model
Intercomparison Project](https://www.geosci-model-dev.net/9/3231/2016/gmd-9-3231-2016.pdf) but the paper does not mention the _basin_ dimension. It only mentions the _basin region_ variable (that defines a mask for 10 regions)

**Comment by jypeter** [comment]
I have eventually followed the right sequence of links and found a DR web page defining the same _basin_ dimension as the json file mentioned above: http://clipc-services.ceda.ac.uk/dreq/u/dim:basin.html

Before finding that information, I also asked James Orr, our local _OMIP paper_ author, and he was not able to give me the information. It's strange that the definition of the _basin_ dimension is missing in the OMIP paper. And the fact that the basin dimension has 3 **basins** that are different from the 10 **basin regions** in the paper may be confusing for some people

**Comment by martinjuckes** [comment]
True, but this is unchanged from CMIP5, so I think it is as intended. It would perhaps have been clearer to call the `basin` dimension something like `basinTransects` -- because it is actually referring to specific transects of special interest which happen to be commonly referred to by the name of the basin they sit in. I'll put a note in the CMIP7 issues (https://github.com/cmip6dr/Request/issues/64) .

**Comment by taylor13** [comment]
These are not north-south transects within a basin (as recorded, e.g., by research vessels).  Rather these are "zonal means" limited to the longitudes included within the basin.  The comment in CMIP5 standard_output provided instructions on how to compute zonal means for ocean models with grid cells no aligned with latitude circles;  thus, the reference to zigzag paths.  Those are paths roughly following a latitude circle used to calculate the zonal mean.

**Comment by martinjuckes** [comment]
Thanks for the clarification .. I'll adjust #64
