### ISSUE TITLE
Update "cell_method", "type" and dimensions for pfull@6hrLev (DR 01.00.16)

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#65]
@martinjuckes we think that _pfull_ in _6hrLev_ should have **area: mean time: point** cell_methods instead of _area: time: mean_

**Comment by jypeter** [comment]
And the value in the **type** column should be either real or float instead of blank. But lots of variables are missing a type: #67

**Comment by martinjuckes** [comment]
Done in 01.00.22
