### ISSUE TITLE
Check the value of the "type" column (DR 01.00.16)

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#67]
@martinjuckes lots of new (I think) variables don't have anything in the **type** column, or sometimes have _float_. It seems that the older variables (e.g. in Amon) have a _real_ type

CF says that [The netCDF data types char, byte, short, int, float or real, and double are all acceptable](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_data_types) but it's probably better to use either float or real, and not both

I expect that the type of most variables will be float/real. I have checked that **basin@0fx** (Region Selection Index) had an **integer** type. Though it should probably be **int** if you follow the CF convention above: https://github.com/cmip6dr/Request/issues/66

**Comment by martinjuckes** [comment]
This has now been fixed.
