### ISSUE TITLE
Many variables missing in AerChemMIP simulations

### ISSUE THREAD

**Issue by pierrenabat** [cmip6dr/Request#71]
We are about to begin our simulations for CMIP6, but there are still a lot of variables missing in AerChemMIP simulations (see my previous email below). Do you plan to correct it in a future version of the data request ?

From: "NABAT Pierre" <pierre.nabat@meteo.fr>
To: "Bill Collins" <w.collins@reading.ac.uk>, "Michael Schulz" <michael.schulz@met.no>
Cc: "MICHOU Martine" <martine.michou@meteo.fr>, "Karl E. Taylor" <taylor13@llnl.gov>, "SENESI Stéphane" <stephane.senesi@meteo.fr>, "Paul J. Durack" <durack1@llnl.gov>, "martin juckes" <martin.juckes@STFC.AC.UK>
Envoyé: Thursday 23 November 2017 12:01:40
Subject: Variables for AerChemMIP simulations in the data request

Dear all,

looking at the variables required for the AerChemMIP simulations in the latest version of the data request (01.00.18), it seems that there are many missing variables.
For example, the piClim-* (http://clipc-services.ceda.ac.uk/dreq/u/8709ad32-51c3-11e7-9bc5-5404a60d96b5.html) and histSST* (http://clipc-services.ceda.ac.uk/dreq/u/8709a922-51c3-11e7-9bc5-5404a60d96b5.html) simulations only require land variables (Lmon), and some others (hist-1950HC, hist-piAer, hist-piNTCF, http://clipc-services.ceda.ac.uk/dreq/u/8709a634-51c3-11e7-9bc5-5404a60d96b5.html) only require ocean variables (Oyr).

There should be at least also atmospheric, aerosol and chemistry variables. If this is a problem in the data request, could you please correct it ?

Best regards,
Pierre Nabat

**Comment by matthew-mizielinski** [comment]
Pierre,

The AerChemMIP request has been in poor shape for some time, and as you say is missing all sorts of variables (see #57 for some examples). I think you'll need to chase the AerChemMIP leads to engage with Martin to get this fixed. I don't think that this is an isolated case; note that the scenarios also need some work (see #59).

M

**Comment by martinjuckes** [comment]
I'm sorry for the slow response. We have had some technical problems at STFC for the last 10 days following a power cut across the site. I have found the problems and should be able to provide an update this week with the missing request in place.

**Comment by MichaelSchulzMETNO** [comment]
Hi Martin, would you need further help from AerChemMIP to identify what is missing? I am a little clueless what to  say more  here than what was in our original AerChemMIP data request excel sheet.

**Comment by matthew-mizielinski** [comment]
@MichaelSchulzMETNO

FYI: A quick comparison of the excel spreadsheet from [here](https://wiki.met.no/aerocom/aerchemmip/diagnostics) suggests that the following CMOR variable names are not present in the data request, but they all have alternatives with the exception of the albedos.
- albs (removed, see cmip6dr/CMIP6_DataRequest_VariableDefinitions#185)
- albsrfc (removed, see cmip6dr/CMIP6_DataRequest_VariableDefinitions#185)
- cnpz (one of the vegHeight variables?)
- convclt (exists as cltc)
- rlutca (exists as rlutaf)
- rlutcsca (exists as rlutcsaf)
- rsutca (exists as rsutaf)
- rsutcsca (exists as rsutcsaf)
- sic (similar variables siconc and siconca exist - see SIMIP for difference to CMIP5 sic)

So the remaining issues with the AerChemMIP request are only the connections between variables and experiments.

**Comment by matthew-mizielinski** [comment]
A quick look at [data request v01.00.19](http://clipc-services.ceda.ac.uk/dreq/tabs03/expt_AerChemMIP_AerChemMIP_3_3.html) suggests that this issue has been dealt with for all experiments starting with "hist" and "ssp370-lowNTCF". The remainder of the experiments listed (piClim* and ssp370*) still appear a bit suspicious in that they have a very small amount of monthly data; 3GB from 30 years.

**Comment by pierrenabat** [comment]
I totally agree with Matthew, only 11 out of the 35 AerChemMIP experiments are ok. For the 24 other experiments (piClim*, sst* except ssp370-lowNTCF), there are still a lot of variables missing, in particular all the atmospheric variables including aerosol and chemistry variables (Amon, AERmon, ...).
Could you please correct it ?

**Comment by matthew-mizielinski** [comment]
From a quick inspection of [v01.00.20](http://clipc-services.ceda.ac.uk/dreq/tabs03/expt_AerChemMIP_AerChemMIP_3_3.html) it looks like this has been fixed, but I have not validated the variables in each experiment.

**Comment by martinjuckes** [comment]
I think this is now resolved. http://clipc-services.ceda.ac.uk/dreq/tabs03/expt_AerChemMIP_AerChemMIP_3_3.html shows the volume requested for each AerChemMIP experiment: the volume is lower for the AerChemMIP5 group, consistent with the submitted template (large volume groups such as Omon and high frequency atmospheric data are not requested for this group).
