### ISSUE TITLE
omldamax requested from AMIP as part of table "day"

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/Request#77]
Why is omldamax (Oday) reqested as part of the deck AMIP experiment?  My understanding of AMIP experiments is that there is no ocean, so requesting the ocean mixed layer thickness seems problematic. 
I am similarly confused by the request for the variables: siconc, sithick, siu, and siv in the SIday variable

**Comment by senesis** [comment]
Some AGCM include sea-ice thermodynamics, which produces quite meaningful siconc and sithick (although quite constrained by forcing SST). This is the case for CNRM-CM, which runs Gealto thermodynamics in AMIP mode

**Comment by martinjuckes** [comment]
OK,
