### ISSUE TITLE
DECK experiments with missing variables

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/Request#8]
I'm looking at the DECK experiment group in version 01.beta.42 and a number of the simulations have an incomplete set of request items. 

Starting from [here](http://clipc-services.ceda.ac.uk/dreq/u/b1147098-aab7-11e6-9fd2-ac72891c3257.html):
  * the `amip` experiment appears to only have VIACSAB requests.
  * the `abrupt-4xCO2` has no requests at all
  * the `picontrol-spinup` also has no requests, but I'm not sure whether this is to be expected.

**Comment by martinjuckes** [comment]
Thanks ..  should be fixed soon.

**Comment by martinjuckes** [comment]
Fixed (certainly before 01.00.11)
