### ISSUE TITLE
Odec should only be linked to the piControl spinup experiments

### ISSUE THREAD

**Issue by sherimickelson** [cmip6dr/Request#80]
From an email conversation with Helene Hewitt:
"I’ve checked my old emails and what Steve and I discussed was saving decadal means for the piControl spinup. Steve-is that also what you intended?"

 and Stephan Griffies:
"Yes, piControl spinup is the intent. "

The below experiments seem to be linked to Odec:
experiment:: 1pctCO2	
experiment:: abrupt-4xCO2	
experiment:: esm-hist	
experiment:: esm-hist-ext
experiment:: esm-piControl	
experiment:: esm-piControl-spinup		
experiment:: historical	
experiment:: historical-ext	
experiment:: piControl	
experiment:: piControl-spinup		
exptgroup:: OmipA		
exptgroup:: OmpiB	

Would it be possible to remove the extra links?

**Comment by durack1** [comment]
@sherimickelson thanks for sorting this!

ping @taylor13 @stephengriffies

**Comment by matthew-mizielinski** [comment]
@sherimickelson, I echo @durack1's thanks for raising this.

I'd welcome confirmation of this, i.e. that decadal means are **only** requested from the piControl-spinup as mentioned at the end of section 3.3 of the OMIP GMD paper? We have planned for some work on adding decadal meaning to our processing chain, but if this is only required for a single simulation (per model), then we can do this in a more ad-hoc fashion.

**Comment by taylor13** [comment]
The quoted email messages (above) from Helene Hewitt and Steve Griffies should serve as definitive confirmation.  Steve was the leader of the group requesting ocean model output.

**Comment by matthew-mizielinski** [comment]
Marvellous, thanks.

**Comment by martinjuckes** [comment]
@taylor13 : OK, I'm removing the request from everything except piControl-spinup. Unless I hear otherwise, I'll assume that all means no request from Odec for esm-piControl-spinup.

**Comment by durack1** [comment]
@martinjuckes thanks for this, I suggest that we keep the request active for `piControl-spinup` AND `esm-piControl-spinup` as they are effectively identical experiments, just the models contributing to them are different.

**Comment by StephenGriffies** [comment]
I concur with @durack1, we need Odec for  both piControl-spinup AND esm-piControl-spinup.

**Comment by martinjuckes** [comment]
OK .. that is what I would have expected .. if the message above hadn't explicitly included esm-piControl-spinup in the list to be removed. I'll include both piControl-spinup and esm-piControl-spinup.

**Comment by durack1** [comment]
@martinjuckes great, thanks for checking in on this - I think we've achieved the best outcome
