### ISSUE TITLE
PMIP request for data from LUMIP experiments

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/Request#81]
Hello @jypeter, I have been tidying up the PMIP request for data from LUMIP experiments: this became confused because of multiple changes in LUMIP experiment specifications.

The PMIP modifications are as follows:
IdealizedGlobalDeforest --> deforest-globe
IdealizedRegDeforest  -- withdrawn
HistNolulccLnd  --> land-noLu
Histnolulcc01 --> hist-noLu
EsmhistbgcNolulcc -- withdrawn

Does this look OK to you? The list of LUMIP experiments is here: http://clipc-services.ceda.ac.uk/dreq/u/LUMIP.html (this list is missing "land-noLu", but that will be added in 01.00.25)

**Comment by senesis** [comment]
Does the above mean that DR01.00.21 doesn't include a correct description of PMIP data request ?

**Comment by martinjuckes** [comment]
Yes .. there are no new variables, but the requestItems specifying which experiments PMIP would like data from have been updated.
