### ISSUE TITLE
DynVarMIP: inconsistency on periods for data output in DECK experiments

### ISSUE THREAD

**Issue by edwinpgerber** [cmip6dr/Request#90]
It was brought to our attention that there are inconsistencies between the DynVarMIP data request, as spelled out in the GMD paper spelling out the MIP (http://doi.org/10.5194/gmd-9-3413-2016), and the  CMIP6 data request, as found here: http://clipc-services.ceda.ac.uk/dreq/tabs03/expt_DynVar_TOTAL_1_1.html.  

There are two important issues:

(1) As listed in the GMD paper, Table 6, we have requested two 40 year periods in the abrupt-4xCO2 experiment (years 1-40 and 111-150), but this does not appear in the official CMIP6 data request.  

(2) As listed in the GMD paper, Table 6, we ask *only for monthly mean data* for the 1pctCO2 experiment, but the official request appears to ask for daily data for many years.

**Comment by martinjuckes** [comment]
Sorry for the slow response. I'll send an email to Eliza and check.

**Comment by martinjuckes** [comment]
Email to Eliza:

The data request only has a single 40 year period specified. We are also missing information about which 40 year period  should be covered. This applies to all the DECK experiments. For piControl several groups are requesting data from the 40 years corresponding to the last 40 years of the historical simulation. This is specified by a timeSlice record (e.g. http://clipc-services.ceda.ac.uk/dreq/u/_slice_hist55.html).

For the abrupt-4xCO2 experiment, there is a core request for data from years 121-150. It may make sense to extend this and make the DynVarMIP request years 111-150?

The 1pctCO2 period could be the same as the abrupt-4xCO2 period?

AMIP would presumably match historical, and be defined as the last 40 years (1975 onwards).

**Comment by martinjuckes** [comment]
Summary:

-- add "abrupt40" time slice record for for first and last 40 years of abrupt4xCO2;
-- added request items for abrupt4xCO2 for all DynVarMIP request Links;
-- removed requests for daily data from 1pctCO2  expt.
