### ISSUE TITLE
Celcius (instead of Celsius) and several other typos/inconsistencies in the Units

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#96]
@martinjuckes I have just found out while reading the "DR paper" draft and checking the **temperature units**, that they are not declared correctly in the DR. At least when I look at the [Data Request Section: units](http://clipc-services.ceda.ac.uk/dreq/index/units.html) page

I have read the rest of the page, and there are many other typos and inconsistencies. Not sure I got them all. @dnadeau4 Can this affect the CMOR tables?

My apologies for not catching this earlier, but I confess I never navigated to this page before

- Cel**C**ius is incorrectly used instead of Celsius. I suddenly had doubts and had to check wikipedia https://en.wikipedia.org/wiki/Celsius
- depr**I**cated instead of deprecated
- _klogram_ is used 2 times instead of kilogram
- should _Joules per kilogram Kelvin_ be _Joules per kilogram **per** Kelvin_ ?
- should _Joules per unit area_ be _Joules per **square metre**_. There are 6 units that use _per area_.
- Same question as above for _per unit volume_
- is **d** OK in `m s-1 d-1 [mpsd]: Metre per second per day` when the page also defines `day [day]: Day`
- **m-2** is _translated_ in 2 different ways (e.g _Newton per square metre_ and _Watts per metre squared_)
- sometimes the plural form of units is used, sometimes not (e.g. _Grams per square metre_ and _Second per metre_)
- Can **tendency** be part of a unit (e.g. _Mole tendency per second_ and _Mole tendency_, which should btw be _Mole tendency per year_)? This looks more like something that is part of the standard name (e.g. _minus_tendency_of_ocean_mole_content_of_iron_due_to_sedimentation_ on the CF web site)
- this is more an inconsistency, but the _title_ string sometimes start with an uppercase, sometimes not (e.g. _Grams per square metre_ and _kilogram per unit area_)
- sometimes words in the title strings are capitalized, sometimes not (e.g. Micrometers Per Second and _Second per metre_)
- the units seem to use UK English, so _Micrometers Per Second_ should rather use micromet**RES**
- there are 2 units with **kg in the title string**, when it should be the full _kilogram_ word: _Degree Celcius kg per unit area_ and _kg squared per second squared_

**Comment by martinjuckes** [comment]
These strings are there for human readers ... there are no specific rules. Spelling should be correct of course, and consistency is helpful.

Celcius --> Celsius corrected.
depricated --> deprecated
klogram --> kilogram
tendency removed;
All start with upper case;
Metre --> Meter
kg --> Kilogram
unit area/volume --> square/cubic meter
square meter vs. meter squared: consistency improved, some issues open: style guide needs updating.

`d` and `day` are synonyms in UDUNITS and hence CF, so this is OK.

Capitalization: to do ... not a priority at this stage.
