### ISSUE TITLE
What is "Places, States or Reservoirs [places]"?

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#97]
When you are on the [A browsable HTML view of the request page](http://clipc-services.ceda.ac.uk/dreq/index.html), there is a link to a _section_ (or whatever the appropriate name is) called **Places, States or Reservoirs [places]** and I thought I would get a list of the authorized regions

When I follow the link, I get to http://clipc-services.ceda.ac.uk/dreq/index/places.html, but it does not list anything, and the _An abstract entity defining an extensive quantity of something, e.g. liquid water, suspended carbon_ text does not seem relevant to the expected content

**Comment by martinjuckes** [comment]
This was an attempt to create some structure around the description of reservoirs and budgets. Not mature in CMIP6.
